### ISSUE TITLE
(question) Can I create a drawer with navio?

### ISSUE THREAD

**Issue by lakardion** [kanzitelli/rn-navio#2]
Hey guys. Awesome library!

I was wondering whether there's a way right now to create a drawer navigator with navio. And if not, if theres a suggested way to integrate navio with `@react-navigation/drawer` to accomplish that

Thanks!

**Comment by kanzitelli** [comment]
Hi @lakardion! Thank you!

Unfortunately, Navio doesn't provide a drawer functionality at the moment :( but as the library is at the very beginning stage, many functionality will be added. And drawer (`@react-navigation/drawer`) is actually the first on the todo list 😄 Could you share the details of your use case of a drawer component? Because I've used it a few times only (as I think it's not good UX), so more examples would be helpful

That's the way I'm thinking to build it:
```tsx
const navio = Navio.build({
  screens: {...},
  stacks: {...},
  tabs: {...},
  drawer: {
    stack: <one from stacks>,
    content?: <custom drawer content>,
    options?: <drawer options>,
    // maybe something else
  },
})
```

I think it should be enough to achieve at least basic drawer functionality. Also, drawer navigator can be inside other navigators, so this case also should be handled.

Then, I am keeping the issue open until drawer functionality is not done.

**Comment by seanadkinson** [comment]
Cool, I was also hoping for the `drawer` to be implemented.  My use case is that I want to add a Hamburger menu upper left, and be able to open a left navigation menu, and switch to different stacks easily.  What you have drawn up in your pseudo-code would suit my needs nicely.  Thanks!

**Comment by kanzitelli** [comment]
Hi @seanadkinson! Thanks for the use case. Then, I will implement as the pseudo-code states and it would be great if you could test it once it's implemented. I'm just very busy last months with the project but will dedicate some time for open source very soon.

**Comment by kanzitelli** [comment]
Hey @lakardion @seanadkinson! Drawer support has been added in v`0.0.2` and added to readme. Let me know how it works in your cases!
